permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: CodeLiu
  email: liujianglong7@163.com
  link: http://codeliu.com
  weibo: http://www.weibo.com/liujianglong
  github: https://github.com/liujianglong

# 站点信息
title: CodeLiu的博客
description: My personal blog
url: http://codeliu.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-63814051-1 
  url: codeliu.com

# disqus 设置
disqus:
  shortname: codeliu

# 主题设置，自动激活某个标签
active: 博客

# 首页除了最新文章外显示分类
cates: 
  - Blog

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  main: 首页