# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            AndroidHub
tagline:          ''
description:      ' Keep Focus '
url:              www.androidhub.cc

paginate:      10

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : codeliu2016


